#!/usr/bin/env bash
#  Bash script that transfers a file from our client to a server

# checking for for argument requirement
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# allocating variable to the arguments
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# To disable strict host key checking
scp -o "StrictHostKeyChecking=no" -i '$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@IP:~/"
