#!/usr/bin/env bash
# script to automate your fix of NGINX error (curl 0:80)& bckup previous nginx default file
mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
