#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code,
# and displays this data
# 	OCCURENCE_NUMBER IP HTTP_CODE in list format

awk -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
