#!/usr/bin/env bash
# script that displays Best School 10 times
# 9th iteration, displays Best School and then Hi
z=1
while [ "$z" -le 10 ]
do
	echo "Best School"
	if [ "$z" -eq 9 ]
	then
		echo "Hi"
	fi
	(( z++ ))
done
