#!/usr/bin/env bash
# Script that does the following:
#	displays bad luck for the 4th loop iteration
#	displays good luck for the 8th loop iteration
#	displays Best School for the other iterations
z=1
while [ $z -le 10 ]
do
	if [ $z -eq 4 ]
	then
	    echo "bad luck"
	elif [ $z -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Best School"
	fi
	((z++))
done
