#!/usr/bin/env bash
# Script that configures the container to fit these requirements:
#	nginx must be running as nginx user
#	nginx must be listening on all active IPs on port 8080

# Replacing #user www-data with user nginx and occurence of 80 to 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# make othes reand-only
chmod 644 /etc/nginx/nginx.conf
# terminating all processes
pkill apache2
# restarting the nginx
sudo -u nginx service nginx start
