#!/usr/bin/env bash
# Script to gracefully reload Gunicorn processes.

# Check if any Gunicorn processes are running
# if ! pgrep gunicorn >/dev/null; then
if [ -z $(pgrep gunicorn) ]; then
    echo "No Gunicorn process found."
    exit 1
fi

# Gracefully terminate running Gunicorn processes
echo "Terminating running Gunicorn processes..."
for pid in $(pgrep gunicorn); do
    kill -HUP "$pid"
done

# Wait for processes to complete gracefully
echo "Waiting for processes to complete gracefully..."
sleep 5

echo "Reload complete"
